FROM nginx:latest


WORKDIR /root


RUN apt-get update \
    && apt-get install -y nano net-tools iputils-ping dos2unix openssh-server openssh-client git curl nodejs npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Crear la carpeta para descargar los archivos
RUN mkdir -p /root/api

# Copiar start.sh
COPY rjsscripts/rjsstart.sh /root/start.sh
RUN chmod +x /root/start.sh

# Set entrypoint
ENTRYPOINT ["/root/start.sh"]

# Configure SSH
EXPOSE 3001
EXPOSE 3000
EXPOSE 3009
EXPOSE 5432
EXPOSE 5433